choco install -y 7zip
choco install -y git.install -params /GitOnlyOnPath
choco install -y fiddler4
choco install -y sysinternals
choco install -y webstorm
choco install -y googlechrome
choco install -y firefox
choco install -y powershell
choco install -y cmder
choco install -y nodejs.install
choco install -y jre8
choco install -y notepadplusplus.install
choco install -y linqpad4
choco install -y NugetPackageExplorer
choco install -y reflector
choco install -y beyondcompare
choco install -y git-credential-manager-for-windows
choco install -y processhacker
choco install -y resharper